name = "PortfolioTools"
uuid = "688f4c35-73fa-4f4a-89f5-eaf16b91200a"
authors = ["Patrick Aschermayr <p.aschermayr@gmail.com>"]
version = "1.0.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
SimpleUnPack = "1"
julia = "^1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
